export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_MOVIES = 'SET_MOVIES';
export const SET_FILTER_BY = 'SET_FILTER_BY';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_MOVIE_PREVIEW = 'SET_MOVIE_PREVIEW';
export const CLEAR_MOVIE_PREVIEW = 'CLEAR_MOVIE_PREVIEW';
